//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IHotelService")]
    public interface IHotelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoom/GetRoom", ReplyAction="http://tempuri.org/IServiceRoom/GetRoomResponse")]
        System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table> GetRoom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoom/GetRoom", ReplyAction="http://tempuri.org/IServiceRoom/GetRoomResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table>> GetRoomAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoom/Time_GetRoom", ReplyAction="http://tempuri.org/IServiceRoom/Time_GetRoomResponse")]
        System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table> Time_GetRoom(System.DateTime begin, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoom/Time_GetRoom", ReplyAction="http://tempuri.org/IServiceRoom/Time_GetRoomResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table>> Time_GetRoomAsync(System.DateTime begin, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoom/addTime_Room", ReplyAction="http://tempuri.org/IServiceRoom/addTime_RoomResponse")]
        void addTime_Room(System.DateTime begin, System.DateTime end, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRoom/addTime_Room", ReplyAction="http://tempuri.org/IServiceRoom/addTime_RoomResponse")]
        System.Threading.Tasks.Task addTime_RoomAsync(System.DateTime begin, System.DateTime end, int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/AddClient", ReplyAction="http://tempuri.org/IHotelService/AddClientResponse")]
        void AddClient(string mobile_, string pass_, string email_, string food_, string lastName_, string firstName_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/AddClient", ReplyAction="http://tempuri.org/IHotelService/AddClientResponse")]
        System.Threading.Tasks.Task AddClientAsync(string mobile_, string pass_, string email_, string food_, string lastName_, string firstName_);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Autorisationn", ReplyAction="http://tempuri.org/IHotelService/AutorisationnResponse")]
        Hotel.DataModel.Client_Tenant Autorisationn(string login, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Autorisationn", ReplyAction="http://tempuri.org/IHotelService/AutorisationnResponse")]
        System.Threading.Tasks.Task<Hotel.DataModel.Client_Tenant> AutorisationnAsync(string login, string pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelServiceChannel : WpfAppClient.ServiceReference1.IHotelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServiceClient : System.ServiceModel.ClientBase<WpfAppClient.ServiceReference1.IHotelService>, WpfAppClient.ServiceReference1.IHotelService {
        
        public HotelServiceClient() {
        }
        
        public HotelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table> GetRoom() {
            return base.Channel.GetRoom();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table>> GetRoomAsync() {
            return base.Channel.GetRoomAsync();
        }
        
        public System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table> Time_GetRoom(System.DateTime begin, System.DateTime end) {
            return base.Channel.Time_GetRoom(begin, end);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Hotel.DataModel.Room.Room_Table>> Time_GetRoomAsync(System.DateTime begin, System.DateTime end) {
            return base.Channel.Time_GetRoomAsync(begin, end);
        }
        
        public void addTime_Room(System.DateTime begin, System.DateTime end, int number) {
            base.Channel.addTime_Room(begin, end, number);
        }
        
        public System.Threading.Tasks.Task addTime_RoomAsync(System.DateTime begin, System.DateTime end, int number) {
            return base.Channel.addTime_RoomAsync(begin, end, number);
        }
        
        public void AddClient(string mobile_, string pass_, string email_, string food_, string lastName_, string firstName_) {
            base.Channel.AddClient(mobile_, pass_, email_, food_, lastName_, firstName_);
        }
        
        public System.Threading.Tasks.Task AddClientAsync(string mobile_, string pass_, string email_, string food_, string lastName_, string firstName_) {
            return base.Channel.AddClientAsync(mobile_, pass_, email_, food_, lastName_, firstName_);
        }
        
        public Hotel.DataModel.Client_Tenant Autorisationn(string login, string pass) {
            return base.Channel.Autorisationn(login, pass);
        }
        
        public System.Threading.Tasks.Task<Hotel.DataModel.Client_Tenant> AutorisationnAsync(string login, string pass) {
            return base.Channel.AutorisationnAsync(login, pass);
        }
    }
}
